### ISSUE TITLE
Síntesis Gestión de Proyectos

### ISSUE THREAD

**Issue by Brisa-4** [SistemasTecTlaxiaco/actividad-3-sintesis-Brisa-4#2]

**Comment by Brisa-4** [comment]
[Síntesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-Brisa-4/files/9464639/Sintesis.pdf)

**Comment by Ferch0419** [comment]
Excelente trabajo: 20/20.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
